# Funding links for the Codifide project
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors (if/when set up)
# github: [codifide]

# Custom sponsorship URL
custom: ["https://www.codifide.com/#contact"]
